apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: data
  name: data
spec:
  replicas: 1 
  selector:
    matchLabels:
      io.kompose.service: data
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.network/myapp: "true"
        io.kompose.service: data
    spec:
      containers:
              # - env:
              # - name: MYSQL_ALLOW_EMPTY_PASSWORD
              #  value: "yes"
      - envFrom:
        - secretRef:
                name: data-service-secret
    #   - name: MYSQL_DATABASE
    #       value: mydatabase
    #    - name: MYSQL_PASSWORD
    #     value: root
    #     - name: MYSQL_ROOT_PASSWORD
    #      value: root
        image: rukiyakomilova/data:v1
        name: data
        ports:
        - containerPort: 3306
        resources: {}
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Secret
metadata:
  name: data-service-secret
type: Opaque
data:
  MYSQL_DATABASE: bXlkYXRhYmFzZQ==
  MYSQL_PASSWORD: cm9vdA==
  MYSQL_ROOT_PASSWORD: cm9vdA==                                        
