apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: data
  name: data
spec:
  serviceName: data
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: data
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.network/myapp: "true"
        io.kompose.service: data
    spec:
      containers:
        - name: data
          image: rukiyakomilova/data:v1
          env:
            - name: MYSQL_DATABASE 
              valueFrom:
                secretKeyRef:
                  name: data-service-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_PASSWORD 
              valueFrom: 
                secretKeyRef: 
                  name: data-service-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: data-service-secret
                  key: MYSQL_ROOT_PASSWORD
        # - env:
    # - name: MYSQL_ALLOW_EMPTY_PASSWORD
    #  value: "yes"
    #   - name: MYSQL_DATABASE
    #       value: mydatabase
    #    - name: MYSQL_PASSWORD
    #     value: root
    #     - name: MYSQL_ROOT_PASSWORD
    #      value: root
          ports:
          - containerPort: 3306
          volumeMounts:   
          - name: data
            mountPath: /var/lib/mysql
            subPath: mysql
  volumeClaimTemplates: #only statefulset has this
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "data-sc"
      resources:
        requests:
          storage: 4Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: data-service-secret
type: Opaque
data:
  MYSQL_DATABASE: bXlkYXRhYmFzZQ==
  MYSQL_PASSWORD: cm9vdA==
  MYSQL_ROOT_PASSWORD: cm9vdA==
