version: "3"
services:

  front:
    image: rukiyakomilova/front:v1
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - myapp

  back:
    image: rukiyakomilova/quotes-back:v1
    build:
      context: back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - myapp

  data:
    image: rukiyakomilova/data:v1
    build:
      context: data
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "mydatabase"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - myapp

  data-script:
    image: rukiyakomilova/data-script:v1
    build:
      context: data-script
      dockerfile: Dockerfile
    networks:
      - myapp

networks:
  myapp:
